#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from 3ac.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "3ac.y"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
extern int yylex();
extern int yyparse();
extern FILE *yyin;
int n=0;
int labelCount=0;

#line 12 "3ac.y"
typedef union{
struct t{
char* code;
char str[1000];
union{
int ival;
float fval;
}v;}t;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	T_LT	258
#define	T_GT	259
#define	T_LE	260
#define	T_GE	261
#define	T_EQUAL	262
#define	T_UNEQUAL	263
#define	T_PLUS	264
#define	T_MINUS	265
#define	T_OR	266
#define	T_MUL	267
#define	T_DIV	268
#define	T_MOD	269
#define	T_AND	270
#define	T_NOT	271
#define	T_PROGRAM	272
#define	T_VAR	273
#define	T_INT	274
#define	T_REAL	275
#define	T_ID	276
#define	T_STRING	277
#define	T_BEGIN	278
#define	T_END	279
#define	T_READ	280
#define	T_WRITE	281
#define	T_IF	282
#define	T_THEN	283
#define	T_ELSE	284
#define	T_WHILE	285
#define	T_DO	286
#define	T_TO	287
#define	T_DOWNTO	288
#define	T_FOR	289
#define	T_ASSIGN	290
#define	T_LB	291
#define	T_RB	292
#define	T_LP	293
#define	T_RP	294
#define	T_SEMI	295
#define	T_DOT	296
#define	T_DOTDOT	297
#define	T_COMMA	298
#define	T_COLON	299
#define	T_INTEGER_TYPE	300
#define	T_BOOLEAN_TYPE	301
#define	T_CHAR_TYPE	302
#define	T_REAL_TYPE	303
#define	T_ARRAY	304
#define	T_OF	305


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int T_LT;
static const int T_GT;
static const int T_LE;
static const int T_GE;
static const int T_EQUAL;
static const int T_UNEQUAL;
static const int T_PLUS;
static const int T_MINUS;
static const int T_OR;
static const int T_MUL;
static const int T_DIV;
static const int T_MOD;
static const int T_AND;
static const int T_NOT;
static const int T_PROGRAM;
static const int T_VAR;
static const int T_INT;
static const int T_REAL;
static const int T_ID;
static const int T_STRING;
static const int T_BEGIN;
static const int T_END;
static const int T_READ;
static const int T_WRITE;
static const int T_IF;
static const int T_THEN;
static const int T_ELSE;
static const int T_WHILE;
static const int T_DO;
static const int T_TO;
static const int T_DOWNTO;
static const int T_FOR;
static const int T_ASSIGN;
static const int T_LB;
static const int T_RB;
static const int T_LP;
static const int T_RP;
static const int T_SEMI;
static const int T_DOT;
static const int T_DOTDOT;
static const int T_COMMA;
static const int T_COLON;
static const int T_INTEGER_TYPE;
static const int T_BOOLEAN_TYPE;
static const int T_CHAR_TYPE;
static const int T_REAL_TYPE;
static const int T_ARRAY;
static const int T_OF;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,T_LT=258
	,T_GT=259
	,T_LE=260
	,T_GE=261
	,T_EQUAL=262
	,T_UNEQUAL=263
	,T_PLUS=264
	,T_MINUS=265
	,T_OR=266
	,T_MUL=267
	,T_DIV=268
	,T_MOD=269
	,T_AND=270
	,T_NOT=271
	,T_PROGRAM=272
	,T_VAR=273
	,T_INT=274
	,T_REAL=275
	,T_ID=276
	,T_STRING=277
	,T_BEGIN=278
	,T_END=279
	,T_READ=280
	,T_WRITE=281
	,T_IF=282
	,T_THEN=283
	,T_ELSE=284
	,T_WHILE=285
	,T_DO=286
	,T_TO=287
	,T_DOWNTO=288
	,T_FOR=289
	,T_ASSIGN=290
	,T_LB=291
	,T_RB=292
	,T_LP=293
	,T_RP=294
	,T_SEMI=295
	,T_DOT=296
	,T_DOTDOT=297
	,T_COMMA=298
	,T_COLON=299
	,T_INTEGER_TYPE=300
	,T_BOOLEAN_TYPE=301
	,T_CHAR_TYPE=302
	,T_REAL_TYPE=303
	,T_ARRAY=304
	,T_OF=305


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::T_LT=258;
const int YY_parse_CLASS::T_GT=259;
const int YY_parse_CLASS::T_LE=260;
const int YY_parse_CLASS::T_GE=261;
const int YY_parse_CLASS::T_EQUAL=262;
const int YY_parse_CLASS::T_UNEQUAL=263;
const int YY_parse_CLASS::T_PLUS=264;
const int YY_parse_CLASS::T_MINUS=265;
const int YY_parse_CLASS::T_OR=266;
const int YY_parse_CLASS::T_MUL=267;
const int YY_parse_CLASS::T_DIV=268;
const int YY_parse_CLASS::T_MOD=269;
const int YY_parse_CLASS::T_AND=270;
const int YY_parse_CLASS::T_NOT=271;
const int YY_parse_CLASS::T_PROGRAM=272;
const int YY_parse_CLASS::T_VAR=273;
const int YY_parse_CLASS::T_INT=274;
const int YY_parse_CLASS::T_REAL=275;
const int YY_parse_CLASS::T_ID=276;
const int YY_parse_CLASS::T_STRING=277;
const int YY_parse_CLASS::T_BEGIN=278;
const int YY_parse_CLASS::T_END=279;
const int YY_parse_CLASS::T_READ=280;
const int YY_parse_CLASS::T_WRITE=281;
const int YY_parse_CLASS::T_IF=282;
const int YY_parse_CLASS::T_THEN=283;
const int YY_parse_CLASS::T_ELSE=284;
const int YY_parse_CLASS::T_WHILE=285;
const int YY_parse_CLASS::T_DO=286;
const int YY_parse_CLASS::T_TO=287;
const int YY_parse_CLASS::T_DOWNTO=288;
const int YY_parse_CLASS::T_FOR=289;
const int YY_parse_CLASS::T_ASSIGN=290;
const int YY_parse_CLASS::T_LB=291;
const int YY_parse_CLASS::T_RB=292;
const int YY_parse_CLASS::T_LP=293;
const int YY_parse_CLASS::T_RP=294;
const int YY_parse_CLASS::T_SEMI=295;
const int YY_parse_CLASS::T_DOT=296;
const int YY_parse_CLASS::T_DOTDOT=297;
const int YY_parse_CLASS::T_COMMA=298;
const int YY_parse_CLASS::T_COLON=299;
const int YY_parse_CLASS::T_INTEGER_TYPE=300;
const int YY_parse_CLASS::T_BOOLEAN_TYPE=301;
const int YY_parse_CLASS::T_CHAR_TYPE=302;
const int YY_parse_CLASS::T_REAL_TYPE=303;
const int YY_parse_CLASS::T_ARRAY=304;
const int YY_parse_CLASS::T_OF=305;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		162
#define	YYFLAG		-32768
#define	YYNTBASE	51

#define YYTRANSLATE(x) ((unsigned)(x) <= 305 ? yytranslate[x] : 81)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45,
    46,    47,    48,    49,    50
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     7,    10,    11,    14,    16,    21,    25,    27,    29,
    31,    33,    35,    37,    39,    46,    50,    52,    55,    59,
    63,    66,    68,    70,    72,    74,    76,    78,    81,    85,
    89,    93,    95,   100,   102,   104,   108,   110,   114,   117,
   121,   125,   129,   133,   137,   142,   146,   151,   158,   163,
   172,   181,   183,   185,   187,   190,   195,   199,   203,   207,
   211,   215,   219,   223,   227,   229,   233,   236,   240,   244,
   248,   252,   256,   258,   260,   262,   264
};

static const short yyrhs[] = {    17,
    21,    40,    52,    61,    41,     0,    18,    53,     0,     0,
    53,    54,     0,    54,     0,    55,    44,    56,    40,     0,
    55,    43,    21,     0,    21,     0,    57,     0,    58,     0,
    45,     0,    46,     0,    47,     0,    48,     0,    49,    36,
    59,    37,    50,    57,     0,    60,    42,    60,     0,    80,
     0,    10,    80,     0,    23,    62,    24,     0,    63,    40,
    62,     0,    63,    40,     0,    64,     0,    67,     0,    69,
     0,    72,     0,    73,     0,    74,     0,    26,    65,     0,
    38,    22,    39,     0,    38,    66,    39,     0,    21,    43,
    66,     0,    21,     0,    25,    38,    68,    39,     0,    21,
     0,    71,     0,    21,    35,    70,     0,    79,     0,    38,
    70,    39,     0,    10,    70,     0,    70,     9,    70,     0,
    70,    10,    70,     0,    70,    12,    70,     0,    70,    13,
    70,     0,    70,    14,    70,     0,    21,    36,    79,    37,
     0,    23,    62,    24,     0,    27,    75,    28,    72,     0,
    27,    75,    28,    72,    29,    72,     0,    30,    75,    31,
    72,     0,    34,    21,    35,    78,    33,    78,    31,    72,
     0,    34,    21,    35,    78,    32,    78,    31,    72,     0,
    76,     0,    77,     0,    21,     0,    16,    76,     0,    16,
    38,    76,    39,     0,    76,    15,    76,     0,    76,    11,
    76,     0,    78,     7,    78,     0,    78,     8,    78,     0,
    78,     3,    78,     0,    78,     4,    78,     0,    78,     5,
    78,     0,    78,     6,    78,     0,    79,     0,    38,    78,
    39,     0,    16,    76,     0,    78,     9,    78,     0,    78,
    10,    78,     0,    78,    12,    78,     0,    78,    13,    78,
     0,    78,    14,    78,     0,    21,     0,    80,     0,    71,
     0,    19,     0,    20,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    47,    54,    55,    58,    59,    62,    65,    66,    69,    70,
    73,    74,    75,    76,    79,    82,    85,    85,    88,    91,
    92,    95,    96,    97,    98,    99,   100,   103,   106,   107,
   110,   111,   114,   117,   118,   121,   124,   125,   128,   129,
   130,   131,   132,   133,   135,   139,   142,   143,   146,   147,
   148,   151,   152,   155,   156,   157,   158,   159,   162,   163,
   164,   165,   166,   167,   170,   171,   172,   173,   174,   175,
   176,   177,   180,   181,   182,   185,   186
};

static const char * const yytname[] = {   "$","error","$illegal.","T_LT","T_GT",
"T_LE","T_GE","T_EQUAL","T_UNEQUAL","T_PLUS","T_MINUS","T_OR","T_MUL","T_DIV",
"T_MOD","T_AND","T_NOT","T_PROGRAM","T_VAR","T_INT","T_REAL","T_ID","T_STRING",
"T_BEGIN","T_END","T_READ","T_WRITE","T_IF","T_THEN","T_ELSE","T_WHILE","T_DO",
"T_TO","T_DOWNTO","T_FOR","T_ASSIGN","T_LB","T_RB","T_LP","T_RP","T_SEMI","T_DOT",
"T_DOTDOT","T_COMMA","T_COLON","T_INTEGER_TYPE","T_BOOLEAN_TYPE","T_CHAR_TYPE",
"T_REAL_TYPE","T_ARRAY","T_OF","S","var_declaration","var_decl_list","var_decl",
"name_list","type_dec","type","array_type_decl","x","const_value","main","stmt_list",
"stmt","write_stmt","x1","variable_list","read_stmt","y","assign_stmt","assign_expr",
"array_access","block_stmt","cond_stmt","loop_stmt","condition","boolean_expr",
"relational_expr","expr","id","num",""
};
#endif

static const short yyr1[] = {     0,
    51,    52,    52,    53,    53,    54,    55,    55,    56,    56,
    57,    57,    57,    57,    58,    59,    60,    60,    61,    62,
    62,    63,    63,    63,    63,    63,    63,    64,    65,    65,
    66,    66,    67,    68,    68,    69,    70,    70,    70,    70,
    70,    70,    70,    70,    71,    72,    73,    73,    74,    74,
    74,    75,    75,    76,    76,    76,    76,    76,    77,    77,
    77,    77,    77,    77,    78,    78,    78,    78,    78,    78,
    78,    78,    79,    79,    79,    80,    80
};

static const short yyr2[] = {     0,
     6,     2,     0,     2,     1,     4,     3,     1,     1,     1,
     1,     1,     1,     1,     6,     3,     1,     2,     3,     3,
     2,     1,     1,     1,     1,     1,     1,     2,     3,     3,
     3,     1,     4,     1,     1,     3,     1,     3,     2,     3,
     3,     3,     3,     3,     4,     3,     4,     6,     4,     8,
     8,     1,     1,     1,     2,     4,     3,     3,     3,     3,
     3,     3,     3,     3,     1,     3,     2,     3,     3,     3,
     3,     3,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     0,
     0,     0,     3,     0,     0,     8,     2,     5,     0,     0,
     0,     4,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    22,    23,    24,    25,    26,    27,     1,
     7,    11,    12,    13,    14,     0,     0,     9,    10,     0,
     0,     0,     0,    28,     0,    76,    77,    73,     0,    75,
     0,    52,    53,     0,    65,    74,     0,     0,    19,    21,
     0,     6,     0,    73,     0,    36,    37,    46,    34,     0,
    35,    32,     0,     0,     0,    54,     0,    67,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,    20,     0,     0,
     0,    17,    39,     0,     0,     0,     0,     0,     0,    33,
     0,    29,    30,    55,     0,     0,    67,    66,    47,    58,
    57,    61,    62,    63,    64,    59,    60,    68,    69,    70,
    71,    72,    49,     0,    18,     0,     0,    38,    40,    41,
    42,    43,    44,    31,    56,    45,     0,     0,     0,     0,
    16,    48,     0,     0,    15,     0,     0,    51,    50,     0,
     0,     0
};

static const short yydefgoto[] = {   160,
     5,     7,     8,     9,    37,    38,    39,   100,   101,    11,
    22,    23,    24,    44,    74,    25,    70,    26,    66,    50,
    27,    28,    29,    51,    52,    53,    54,    55,    56
};

static const short yypact[] = {   -15,
     0,   -35,    -7,    39,    40,-32768,    39,-32768,    28,   132,
    38,-32768,    62,   103,    54,   132,    60,    65,   116,   116,
    75,    84,    72,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,    82,   121,-32768,-32768,    -3,
   100,   122,    12,-32768,   -13,-32768,-32768,    73,   126,-32768,
   128,    58,-32768,   164,-32768,-32768,   129,   130,-32768,   132,
    -6,-32768,    -3,   127,    -3,    10,-32768,-32768,   127,   136,
-32768,   138,   152,   153,   -13,-32768,    81,    59,   120,    81,
    18,   171,    81,    81,   126,   126,   126,   126,   126,   126,
   126,   126,   126,   126,   126,   171,   126,-32768,    86,   156,
   154,-32768,   173,    68,    -3,    -3,    -3,    -3,    -3,-32768,
   174,-32768,-32768,-32768,    47,   160,    58,-32768,   169,   184,
-32768,   170,   170,   170,   170,   170,   170,   176,   176,-32768,
-32768,-32768,-32768,   101,-32768,   150,    -6,-32768,   173,   173,
-32768,-32768,-32768,-32768,-32768,-32768,   171,   126,   126,    83,
-32768,-32768,   107,   113,-32768,   171,   171,-32768,-32768,   201,
   202,-32768
};

static const short yypgoto[] = {-32768,
-32768,-32768,   196,-32768,-32768,    55,-32768,-32768,    67,-32768,
   -10,-32768,-32768,-32768,    95,-32768,-32768,-32768,   -53,   165,
   -81,-32768,-32768,   188,   -16,-32768,   -49,   -14,   -52
};


#define	YYLAST		208


static const short yytable[] = {    81,
   119,     1,    75,    99,     3,    41,    63,    76,   102,   103,
     4,   104,    46,    47,   133,    46,    47,    64,   105,   106,
     2,   107,   108,   109,    77,    67,    91,    92,    78,    93,
    94,    95,    72,    73,    65,   122,   123,   124,   125,   126,
   127,   128,   129,   130,   131,   132,   135,   134,    67,    98,
    67,   139,   140,   141,   142,   143,   118,    83,   114,     6,
   115,    84,    10,   117,   116,   152,   120,   121,    83,   -55,
    13,    14,    84,   -55,   158,   159,   105,   106,    30,   107,
   108,   109,    31,   -54,   102,   145,   -55,   -54,    40,   -55,
    67,    67,    67,    67,    67,    58,    75,    42,   153,   154,
   -54,    76,    43,   -54,    46,    47,   138,    59,    79,    91,
    92,    60,    93,    94,    95,    91,    92,    61,    93,    94,
    95,    91,    92,    68,    93,    94,    95,    32,    33,    34,
    35,    45,   148,   149,    46,    47,    48,   156,    46,    47,
    64,    80,    69,   157,    46,    47,    64,    32,    33,    34,
    35,    36,    15,    49,    16,    82,    17,    18,    19,    96,
    62,    20,    79,    49,    97,    21,    85,    86,    87,    88,
    89,    90,    91,    92,   110,    93,    94,    95,    91,    92,
   111,    93,    94,    95,   107,   108,   109,    93,    94,    95,
   112,   113,   136,    16,    72,   137,   146,   147,    84,   150,
   161,   162,    12,   151,   155,   144,    71,    57
};

static const short yycheck[] = {    49,
    82,    17,    16,    10,    40,    16,    10,    21,    61,    63,
    18,    65,    19,    20,    96,    19,    20,    21,     9,    10,
    21,    12,    13,    14,    38,    40,     9,    10,    45,    12,
    13,    14,    21,    22,    38,    85,    86,    87,    88,    89,
    90,    91,    92,    93,    94,    95,    99,    97,    63,    60,
    65,   105,   106,   107,   108,   109,    39,    11,    75,    21,
    77,    15,    23,    80,    79,   147,    83,    84,    11,    11,
    43,    44,    15,    15,   156,   157,     9,    10,    41,    12,
    13,    14,    21,    11,   137,    39,    28,    15,    35,    31,
   105,   106,   107,   108,   109,    21,    16,    38,   148,   149,
    28,    21,    38,    31,    19,    20,    39,    24,    36,     9,
    10,    40,    12,    13,    14,     9,    10,    36,    12,    13,
    14,     9,    10,    24,    12,    13,    14,    45,    46,    47,
    48,    16,    32,    33,    19,    20,    21,    31,    19,    20,
    21,    16,    21,    31,    19,    20,    21,    45,    46,    47,
    48,    49,    21,    38,    23,    28,    25,    26,    27,    31,
    40,    30,    36,    38,    35,    34,     3,     4,     5,     6,
     7,     8,     9,    10,    39,    12,    13,    14,     9,    10,
    43,    12,    13,    14,    12,    13,    14,    12,    13,    14,
    39,    39,    37,    23,    21,    42,    37,    29,    15,    50,
     0,     0,     7,   137,   150,   111,    42,    20
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 48 "3ac.y"
{
        printf("%s",yyvsp[-1].t.code);
        return 0;
;
    break;}
case 2:
#line 54 "3ac.y"
{;
    break;}
case 3:
#line 55 "3ac.y"
{;
    break;}
case 19:
#line 88 "3ac.y"
{yyval.t.code=yyvsp[-1].t.code;;
    break;}
case 20:
#line 91 "3ac.y"
{handle_stmt(&yyval.t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 21:
#line 92 "3ac.y"
{yyval.t.code=yyvsp[-1].t.code;;
    break;}
case 22:
#line 95 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;;
    break;}
case 23:
#line 96 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;;
    break;}
case 24:
#line 97 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;;
    break;}
case 25:
#line 98 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;;
    break;}
case 26:
#line 99 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;;
    break;}
case 27:
#line 100 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;;
    break;}
case 28:
#line 103 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 29:
#line 106 "3ac.y"
{write_3ac_type1(&yyval.t,yyvsp[-1].t);;
    break;}
case 30:
#line 107 "3ac.y"
{write_3ac_type2(&yyval.t,yyvsp[-1].t);;
    break;}
case 31:
#line 110 "3ac.y"
{handle_variable_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 32:
#line 111 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 33:
#line 114 "3ac.y"
{read_3ac(&yyval.t,yyvsp[-1].t);;
    break;}
case 34:
#line 117 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 35:
#line 118 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 36:
#line 121 "3ac.y"
{assign_stmt_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 37:
#line 124 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);yyval.t.code=yyvsp[0].t.code;;
    break;}
case 38:
#line 125 "3ac.y"
{strcpy(yyval.t.str,yyvsp[-1].t.str);
      yyval.t.code=yyvsp[-1].t.code;
    ;
    break;}
case 39:
#line 128 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 40:
#line 129 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"+");;
    break;}
case 41:
#line 130 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"-");;
    break;}
case 42:
#line 131 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"*");;
    break;}
case 43:
#line 132 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"/");;
    break;}
case 44:
#line 133 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"%");;
    break;}
case 45:
#line 135 "3ac.y"
{array_access_3ac(&yyval.t,yyvsp[-3].t,yyvsp[-1].t);
    break;}
case 46:
#line 139 "3ac.y"
{yyval.t.code=yyvsp[-1].t.code;;
    break;}
case 47:
#line 142 "3ac.y"
{if_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 48:
#line 143 "3ac.y"
{if_else_3ac(&yyval.t,yyvsp[-4].t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 49:
#line 146 "3ac.y"
{while_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 50:
#line 147 "3ac.y"
{for_downto_3ac(&yyval.t,yyvsp[-6].t,yyvsp[-4].t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 51:
#line 148 "3ac.y"
{for_to_3ac(&yyval.t,yyvsp[-6].t,yyvsp[-4].t,yyvsp[-2].t,yyvsp[0].t);;
    break;}
case 52:
#line 151 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str); yyval.t.code=yyvsp[0].t.code;;
    break;}
case 53:
#line 152 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str); yyval.t.code=yyvsp[0].t.code;;
    break;}
case 54:
#line 155 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 55:
#line 156 "3ac.y"
{not_3ac(&yyval.t,yyvsp[0].t);;
    break;}
case 56:
#line 157 "3ac.y"
{not_3ac(&yyval.t,yyvsp[-1].t);;
    break;}
case 57:
#line 158 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"AND");;
    break;}
case 58:
#line 159 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"OR");;
    break;}
case 59:
#line 162 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"=");;
    break;}
case 60:
#line 163 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"<>");;
    break;}
case 61:
#line 164 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"<");;
    break;}
case 62:
#line 165 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,">");;
    break;}
case 63:
#line 166 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"<=");;
    break;}
case 64:
#line 167 "3ac.y"
{conditional_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,">=");;
    break;}
case 65:
#line 170 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);yyval.t.code=yyvsp[0].t.code;;
    break;}
case 66:
#line 171 "3ac.y"
{strcpy(yyval.t.str,yyvsp[-1].t.str); yyval.t.code=yyvsp[-1].t.code;;
    break;}
case 67:
#line 172 "3ac.y"
{not_3ac(&yyval.t,yyvsp[0].t);;
    break;}
case 68:
#line 173 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"+");;
    break;}
case 69:
#line 174 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"-");;
    break;}
case 70:
#line 175 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"*");;
    break;}
case 71:
#line 176 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"/");;
    break;}
case 72:
#line 177 "3ac.y"
{assign_expr_3ac(&yyval.t,yyvsp[-2].t,yyvsp[0].t,"%");;
    break;}
case 73:
#line 180 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 74:
#line 181 "3ac.y"
{strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 75:
#line 182 "3ac.y"
{yyval.t.code=yyvsp[0].t.code;strcpy(yyval.t.str,yyvsp[0].t.str);;
    break;}
case 76:
#line 185 "3ac.y"
{sprintf(yyval.t.str, "%d", yyvsp[0].t.v.ival);;
    break;}
case 77:
#line 186 "3ac.y"
{sprintf(yyval.t.str, "%f", yyvsp[0].t.v.fval);;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 189 "3ac.y"


char* newLabel() {
    char* label = (char*) malloc(10);
    sprintf(label, "L%d", labelCount++);
    return label;
}

void handle_variable_3ac(struct t* $$,struct t $1,struct t $3){
char *result=calloc(200,sizeof(char));
strcat(result,$1.str);
strcat(result,",");
strcat(result,$3.str);
strcpy($$->str,result);
  
}
void write_3ac_type1(struct t* $$,struct t $2){
	char *result=calloc(200,sizeof(char));
	    sprintf(result,"write(%s)\n",$2.str);
	    $$->code=result;
}

void write_3ac_type2(struct t* $$,struct t $2){
	char *result=calloc(200,sizeof(char));
                if($2.code!=NULL)
    		strcat(result,$2.code);
    		sprintf(result,"write(%s)\n",$2.str);
    		$$->code=result;
}

void read_3ac(struct t* $$, struct t $3) {
    int len = ($3.code != NULL) ? strlen($3.code) : 0;
    size_t total_length = len + strlen($3.str) + 7; // 7 is for "read()" and "\n"
    char *st = calloc(total_length, sizeof(char));
    sprintf(st, "read(%s)\n", $3.str);
    char *result = calloc(total_length, sizeof(char));
    if ($3.code != NULL)
        strcat(result, $3.code);
    strcat(result, st);
    $$->code = result;
    free(st);
}

void for_to_3ac(struct t* $$, struct t $2, struct t $4, struct t $6, struct t $8) {
    char *beginl = newLabel();
    char *endl = newLabel();
    int len1 = ($2.code != NULL) ? strlen($2.code) : 0;
    int len2 = ($4.code != NULL) ? strlen($4.code) : 0;
    int len3 = ($6.code != NULL) ? strlen($6.code) : 0;
    int len4 = ($8.code != NULL) ? strlen($8.code) : 0;
    size_t total_length = len1 + len2 + len3 + len4 + strlen(beginl) + strlen(endl) + 85; // 85 is for the additional characters needed
    char *result = calloc(total_length, sizeof(char));
    if ($2.code != NULL)
        strcat(result, $2.code);
    if ($4.code != NULL)
        strcat(result, $4.code);
    if ($6.code != NULL)
        strcat(result, $6.code);
    char *st = calloc(total_length, sizeof(char));
    sprintf(st, "%s=%s\n%s:\nif(%s>%s) goto %s\n%sgoto %s\n%s:\n",
             $2.str, $4.str, beginl, $2.str, $6.str, endl, $8.code, beginl, endl);
    strcat(result, st);
    $$->code = result;
    free(st);
}



void for_downto_3ac(struct t* $$, struct t $2, struct t $4, struct t $6, struct t $8) {
    char *beginl = newLabel();
    char *endl = newLabel();
    int len1 = ($2.code != NULL) ? strlen($2.code) : 0;
    int len2 = ($4.code != NULL) ? strlen($4.code) : 0;
    int len3 = ($6.code != NULL) ? strlen($6.code) : 0;
    int len4 = ($8.code != NULL) ? strlen($8.code) : 0;
    size_t total_length = len1 + len2 + len3 + len4 + strlen(beginl) + strlen(endl) + 85; // Adjust as needed
    char *result = calloc(total_length, sizeof(char));
    if ($2.code != NULL)
        strcat(result, $2.code);
    if ($4.code != NULL)
        strcat(result, $4.code);
    if ($6.code != NULL)
        strcat(result, $6.code);
    char *st = calloc(total_length, sizeof(char));
    sprintf(st, "%s=%s\n%s:\nif(%s<%s) goto %s\n%sgoto %s\n%s:\n",
            $2.str, $4.str, beginl, $2.str, $6.str, endl, $8.code, beginl, endl);
    strcat(result, st);
    $$->code = result;
    free(st);
}



void while_3ac(struct t* $$, struct t $2, struct t $4) {
    int len1 = ($2.code != NULL) ? strlen($2.code) : 0;
    int len2 = ($4.code != NULL) ? strlen($4.code) : 0;
    char *beginl = newLabel();
    char *endl = newLabel();
    char *st = calloc(200 + len2 + len1, sizeof(char));
    if (len1 != 0)
        sprintf(st, "%s:\n%sif(NOT %s) goto %s\n%sgoto %s\n%s:\n",
                beginl, $2.code, $2.str, endl, $4.code, beginl, endl);
    else
        sprintf(st, "%s:\nif(NOT %s) goto %s\n%sgoto %s\n%s:\n",
                beginl, $2.str, endl, $4.code, beginl, endl);
    $$->code = st;
}

void if_else_3ac(struct t* $$, struct t $2, struct t $4, struct t $6) {
    int len1 = ($2.code != NULL) ? strlen($2.code) : 0;
    int len2 = ($4.code != NULL) ? strlen($4.code) : 0;
    int len3 = ($6.code != NULL) ? strlen($6.code) : 0;
    char *truel = newLabel();
    char *endl = newLabel();
    char *st = calloc(200 + len3 + len2, sizeof(char));
    sprintf(st, "if(%s) goto %s\n%s\ngoto %s\n%s:\n%s\n%s:\n",
            $2.str, truel, $6.code, endl, truel, $4.code, endl);
    char *result = calloc(len1 + strlen(st) + 1, sizeof(char));
    if ($2.code != NULL)
        strcat(result, $2.code);
    strcat(result, st);
    $$->code = result;
    free(st);
}

void if_3ac(struct t* $$, struct t $2, struct t $4) {
    int len1 = ($2.code != NULL) ? strlen($2.code) : 0;
    int len2 = ($4.code != NULL) ? strlen($4.code) : 0;
    char *endl = newLabel();
    char *st = calloc(200 + len2, sizeof(char));
    sprintf(st, "if(NOT %s) goto %s\n%s%s:\n",
            $2.str, endl, $4.code, endl);
    char *result = calloc(len1 + strlen(st) + 1, sizeof(char));
    if ($2.code != NULL)
        strcat(result, $2.code);
    strcat(result, st);
    $$->code = result;
    free(st);
}

void conditional_3ac(struct t* $$, struct t $1, struct t $3, char *s) {
    char *truel = newLabel();
    char *endl = newLabel();
    char *st = calloc(200, sizeof(char));
    sprintf($$->str, "t%d", n);
    sprintf(st, "if(%s %s %s) goto %s\nt%d=0 \ngoto %s\n%s:\nt%d = 1 \n%s:\n",
            $1.str, s, $3.str, truel, n, endl, truel, n, endl);
    n++;
    int len1 = ($1.code != NULL) ? strlen($1.code) : 0;
    int len2 = ($3.code != NULL) ? strlen($3.code) : 0;
    char *result = calloc(len1 + len2 + strlen(st) + 1, sizeof(char));
    if ($1.code != NULL)
        strcat(result, $1.code);
    if ($3.code != NULL)
        strcat(result, $3.code);
    strcat(result, st);
    $$->code = result;
    free(st);
}

void not_3ac(struct t* $$, struct t $1) {
    char *truel = newLabel();
    char *endl = newLabel();
    char *st = calloc(200, sizeof(char));
    sprintf($$->str, "t%d", n);
    sprintf(st, "if(NOT %s) goto %s\nt%d=0 \ngoto %s\n%s:\nt%d = 1 \n%s:\n",
            $1.str, truel, n, endl, truel, n, endl);
    n++;
    int len1 = ($1.code != NULL) ? strlen($1.code) : 0;
    char *result = calloc(len1 + strlen(st) + 1, sizeof(char));
    if ($1.code != NULL)
        strcat(result, $1.code);
    strcat(result, st);
    $$->code = result;
    free(st);
}

void assign_expr_3ac(struct t* $$, struct t $1, struct t $3, char *op) {
    // Format the temporary variable name
    sprintf($$->str,"t%d", n);
    n++;
    // Build the arithmetic statement
    char *st = calloc(50, sizeof(char));
    strcat(st, $$->str);
    strcat(st, "=");
    strcat(st, $1.str);
    strcat(st, op);
    strcat(st, $3.str);
    strcat(st, "\n");
    // Calculate the total length needed for the result
    int len1 = ($1.code != NULL) ? strlen($1.code) : 0;
    int len2 = ($3.code != NULL) ? strlen($3.code) : 0;
    char *result = calloc(len1 + len2 + strlen(st) + 1, sizeof(char));
    // Concatenate existing code and the new statement
    if ($1.code != NULL)
        strcat(result, $1.code);
    if ($3.code != NULL)
        strcat(result, $3.code);
    strcat(result, st);
    // Assign the new code to lhs and free temporary string
    $$->code = result;
    free(st);
}


void assign_stmt_3ac(struct t* $$, struct t $1, struct t $3) {
    char *st = calloc(50, sizeof(char));
    strcat(st, $1.str);
    strcat(st, "=");
    strcat(st, $3.str);
    strcat(st, "\n");
    int len2 = ($3.code != NULL) ? strlen($3.code) : 0;
    char *result = calloc(len2 + strlen(st) + 1, sizeof(char));
    if ($3.code != NULL)
        strcat(result, $3.code);
    strcat(result, st);
    // Assign the new code to lhs and free temporary string
    $$->code = result;
    free(st);
}

void handle_stmt(struct t* $$, struct t $1, struct t $2) {
    int len1 = ($1.code != NULL) ? strlen($1.code) : 0;
    int len2 = ($2.code != NULL) ? strlen($2.code) : 0;
    char *result = calloc(len1 + len2 + 1, sizeof(char));
    if ($1.code != NULL)
        strcat(result, $1.code);
    if ($2.code != NULL)
        strcat(result, $2.code);
    $$->code = result;
}

void array_access_3ac(struct t* $$, struct t $1, struct t $3) {
    sprintf($$->str, "t%d", n);
    n++;
    char *st = calloc(50, sizeof(char));
    strcat(st, $$->str);
    strcat(st, "=");
    strcat(st, $1.str);
    strcat(st, "[");
    strcat(st, $3.str);
    strcat(st, "]");
    strcat(st, "\n");
    int len2 = ($3.code != NULL) ? strlen($3.code) : 0;
    char *result = calloc(len2 + strlen(st) + 1, sizeof(char));
    if ($3.code != NULL)
        strcat(result, $3.code);
    strcat(result, st);
    $$->code = result;
    free(st);
}

int main() 
{ 
    char filename[100];
    printf("Enter input file name: ");
    scanf("%s", filename);

    yyin = fopen(filename, "r");
    if (yyin == NULL) {
        printf("Error opening file: %s\n", filename);
        return 1;
    }

    yyparse();
    
    fclose(yyin);
    return 0;
}

void yyerror(){
printf("Syntax error..\n");
}
